[tool.poetry]
name = "spark-streaming-project"
version = "0.1.0"
description = ""
authors = ["bele <belesemu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyspark = "^3.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
